package inf112.skeleton.app.gameobjects;

public enum GameObjectType {
    PLAYER,
    PLAYER_NORTH,
    PLAYER_EAST,
    PLAYER_SOUTH,
    PLAYER_WEST,

    REPAIR_STATION,
    FLAG,
    STANDARD_TILE,

    CONVEYOR_WEST,
    CONVEYOR_NORTH,
    CONVEYOR_EAST,
    CONVEYOR_SOUTH,

    FAST_CONVEYOR_WEST,
    FAST_CONVEYOR_NORTH,
    FAST_CONVEYOR_EAST,
    FAST_CONVEYOR_SOUTH,

    WEST_WALL,
    NORTH_WALL,
    EAST_WALL,
    SOUTH_WALL,

    WEST_PUSHER,
    NORTH_PUSHER,
    EAST_PUSHER,
    SOUTH_PUSHER,

    HOLE,

    WEST_LASER_OUTLET,
    NORTH_LASER_OUTLET,
    EAST_LASER_OUTLET,
    SOUTH_LASER_OUTLET,

}
